### ISSUE TITLE
AutoCopy doesn't behave well with optionals

### ISSUE THREAD

**Issue by Arasthel** [bq/mini-swift#7]
Hi!

First of all, the library looks great and I'm eager to test it on some projects as soon as I get back from a work trip. While I know it's not the main focus of the library, the `copy(...)` method generated using Sourcery caught my eye, since that's something I already use on my projects with a similar approach. 

However, after taking a look at the template, I couldn't see how you were handling *nil* values since the default param is also *nil*, so I ran a quick test:

```swift
struct State: AutoCopy {
    let optional: String?
}

let state = State(optional: "Hey")
let copy = state.copy(optional: nil)
// copy.optional is still "Hey"
```

Maybe you have already solved this since you say you're already using the library in production apps but just in case [here is how I solved this](https://arasthel.com/data-classes-on-swift/#selectwhichvalueswillbechangedandwhichwillbecopied) using enums. It's not a perfect solution but it has worked well for me so far.

Also, if you found another solution to the *nil* issue here, I'd be glad to know it, since it might get rid of those enums and make the syntax nicer. Anyway, I hope this was useful.

**Comment by minuscorp** [comment]
we can see `{{variable.name}}: {{variable.typeName }}{% if not variable.isOptional %}?{% endif %} = nil` so I don't quite understand why it won't work 🤔

**Comment by Arasthel** [comment]
The generated extension looks like this:

```swift
extension State {
    func copy(optional: String? = nil) -> State {
        return State(optional: optional ?? self.optional)
    } 
}
```

So 'optional' is explicitly nil because the user wants it that way, but since you do `optional ?? self.optional`, the previous value will always be used.

**Comment by minuscorp** [comment]
Yeah, I was testing that and why that's not making any issues into our codebases. When a `State` has an optional value and gets no value is because that its associated `Task` has errored, and hence the state variable is irrelevant, but it is a bug and I'm going to add what you did (if I can make use of it) in the 5.1 implementation

**Comment by minuscorp** [comment]
I came with a little cleaner way to deal with the `nil` case in `init` time:

```swift
public enum OptionalCopyValue<T>: ExpressibleByNilLiteral {

    case `new`(T)
    case same
    case `nil`
    
    public init(nilLiteral: ()) {
        self = .nil
    }
}
```

**Comment by Arasthel** [comment]
Oh, that's awesome! I would never have thought of using  NilLiteral conformance. I think I'll change it on my templates too, thanks 😄 .

**Comment by minuscorp** [comment]
I was even easing the creation of `new` values using a convenience prefix operator to indicate that the value being passed is a new one, something like this:

```swift
prefix operator *

prefix func * <T>(lhs: T) -> OptionalCopyValue<T> {
    return .new(lhs)
}

let example: OptionalCopyValue<String> = *"hey-ho" // .new("hey-ho")
```
```

**Comment by minuscorp** [comment]
Fixed 😄 thank you!! Feel free to open as many issues as you want
